/* Generated by BuildNumber Version 0.8 */

#ifndef BUILD_NUMBER_H_ 
#define BUILD_NUMBER_H_ 

<<<<<<< HEAD
#define BUILDNUMBER 6949
#define BUILDNUMBER_STR "6949" 
=======
#define BUILDNUMBER 6948
#define BUILDNUMBER_STR "6948" 
>>>>>>> 820b224... Fix PPC2002 font antialiasing problem

#endif /* BUILD_NUMBER_H_ */
