#!/bin/sh
start=`date`
make clean
make TARGET=PPC2002
make TARGET=PPC2003
make TARGET=PNA
make TARGET=PC

echo "DONE -----------"
echo "started $start"
echo "ended `date`"
echo PLEASE UPDATE BUILDNUMBER
