FROM debian:trixie-slim

# Install common prerequisites
RUN apt-get update && \
        apt-get install -y --no-install-recommends \
                sudo wget ca-certificates bash-completion \
                git-core openssh-client pkg-config build-essential \
                xsltproc imagemagick fonts-dejavu fakeroot zip python3 \
                libzzip-dev libboost-dev libfreetype6-dev libpng-dev libgeographiclib-dev \
                libgl1-mesa-dev libegl1-mesa-dev libx11-dev \
                libsdl2-dev libsdl2-mixer-dev \
                libasound2-dev libsndfile1-dev \
                mingw-w64 libfl2 zlib1g-dev libcurl4-openssl-dev && \
        apt-get clean && \
        rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/log/*

# Install PC library dependencies
WORKDIR /tmp/mingw
ADD install-mingw-w64-depends.sh /tmp/mingw/install-mingw-w64-depends.sh
RUN ./install-mingw-w64-depends.sh && \
         rm -rf /tmp/mingw

# Install KOBO toolchain
WORKDIR /tmp/kobo
RUN wget http://lk8000.it/toolchain/arm-kobo-linux-gnueabihf-13.2.0.bookworm.x86_64.tar.xz && \
        tar -xJf arm-kobo-linux-gnueabihf-13.2.0.bookworm.x86_64.tar.xz && \
        mv arm-kobo-linux-gnueabihf /opt/arm-kobo-linux-gnueabihf && \
        rm -rf /tmp/kobo

ENV PATH=$PATH:/opt/arm-kobo-linux-gnueabihf/bin

#build KOBO library dependencies
COPY ./kobo-build-rootfs /tmp/kobo-build-rootfs
WORKDIR /tmp/kobo-build-rootfs
RUN ./build-all.sh && \
        rm -rf /tmp/kobo-build-rootfs
ENV KOBO=/opt/kobo-rootfs

# Install WinCE toolchain
WORKDIR /tmp/WinCE
RUN wget http://lk8000.it/toolchain/arm-mingw32ce-9.3.0.buster.x86_64.tar.xz && \
        tar -xJf arm-mingw32ce-9.3.0.buster.x86_64.tar.xz && \
        mv arm-mingw32ce /opt/arm-mingw32ce && \
        rm -rf /tmp/WinCE

ENV PATH=$PATH:/opt/arm-mingw32ce/bin

# add compiler user
RUN adduser --disabled-password --gecos '' compiler

USER compiler
WORKDIR /home/compiler
VOLUME [ "/home/compiler" ]
